language: python
python:
  - "2.7"
before_install:
  - "export TRAVIS_CI=True"
  - "export DISPLAY=:99.0"
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-pyside python-dbus dbus python-magic
  - "sh -e /etc/init.d/xvfb start"
install:
  - pip install . --use-mirrors
  - pip install -r dev_requirements.txt --use-mirrors
before_script:
  - ln -s /usr/lib/python2.7/dist-packages/PySide /home/travis/virtualenv/python2.7/lib/python2.7/site-packages/PySide -v
  - ln -s /usr/lib/python2.7/dist-packages/dbus /home/travis/virtualenv/python2.7/lib/python2.7/site-packages/dbus -v
  - ln -s /usr/lib/python2.7/dist-packages/_dbus_* /home/travis/virtualenv/python2.7/lib/python2.7/site-packages/ -v
  - ln -s /usr/lib/python2.7/dist-packages/magic.py /home/travis/virtualenv/python2.7/lib/python2.7/site-packages/ -v
  - cp tests/settings/ci_local.py tests/settings/local.py
  - mkdir -p /home/travis/.everpad/data/1/
script:
  - nosetests --with-coverage
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
